{{- if or .Values.redisUsername .Values.redisPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghproxy.fullname" . }}-redis-auth
  labels:
    {{- include "ghproxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redisUsername }}
  redis-username: {{ .Values.redisUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.redisPassword }}
  redis-password: {{ .Values.redisPassword | b64enc | quote }}
  {{- end }}
{{- end }}