apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pia.fullname" . }}-config
  labels:
    {{- include "pia.labels" . | nindent 4 }}
data:
  projects.yaml: |
    {{- range $name, $project := .Values.config.projects }}
    - project_id: {{ $name }}
      {{- toYaml $project | nindent 6 }}
    {{- end }}