{{- if .Values.config.dependencyTrackApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pia.fullname" . }}-secret
  labels:
    {{- include "pia.labels" . | nindent 4 }}
type: Opaque
stringData:
  PIA_DEPENDENCY_TRACK_API_KEY: {{ .Values.config.dependencyTrackApiKey | quote }}
{{- end }}