#
#  *******************************************************************************
#  Copyright (c) 2025 Eclipse Foundation and others.
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License 2.0
#  which is available at http://www.eclipse.org/legal/epl-v20.html
#  SPDX-License-Identifier: EPL-2.0
#  *******************************************************************************
#
apiVersion: v2
name: ghproxy
description: A Helm chart for ghproxy
maintainers:
  - name: eclipse-csi
type: application
version: 0.1.0
appVersion: "v20250422-30713f381"
